version: '2'

services:
  vpnc:
    image: vpnc
    container_name: vpnc 
    build: .
    environment:
      - VPNADDR=${VPNADDR}
      - VPNUSER=${VPNUSER}
    privileged: true
    network_mode: host
